<h1>Accommodation</h1>

        <p>
          Sydney is full of hotels, bnbs, and backpackers of all shapes and sizes. For any non-Aussies out there, it’s important to know that ‘hotel’ in Australia can mean ‘bar with a few rooms tacked on the back’. Feel free to run ideas by us before booking.
        </p><p>

So where should you stay?
</p><p>
If you’re coming to Sydney just for the wedding weekend, we recommend you stay walking distance from Rushcutters Bay. Neighborhoods nearby include Rushcutters Bay itself, Potts Point, Kings Cross, and Edgecliff. Areas of Darlinghurst and Paddington are also close by. 
The closest hotel is the Vibe Hotel (100 Bayswater Rd, Rushcutters Bay NSW 2011). Rooms are about $100/ night. We also recommend airbnb for affordable options in the area. 
</p><p>
If you’re coming to Sydney for longer, don’t feel that you need to confine yourself to the wedding area. Our main recommendation would just be to stay walking distance from a train station. As long as you have that, you can explore quite easily. 

        </p>
        