
          <h1>Reception and ceremony</h1>
       
          Sunday 23 November 12:00pm<br />
          <br />
          RAN Sailing Association (RANSA)<br />
          Sir David Martin Reserve/1C New Beach Rd<br />
          Darling Point NSW 2027<br />
          <a href="https://goo.gl/maps/kYNIE" class="">View on map</a>    <br />
          <br />
                    <p>
          <span class="question">Wedding Schedule</span>
        </p>

          <p>
              
              <b>12:00 - 12:30</b> Ceremony <br />
              <b>12:30 - 1:30</b> Photo break. Drinks and nibbles served.  <br />
              <b>1:30 - 5:30</b> Reception <br />
              <b>5:30 onwards</b> Wedding officially over, though we invite people to stick around for longer as the cleaners won't arrive till 8:30pm and it is a great spot to watch the sun go down.
          </p>
                    <p>
          <span class="question">What to bring</span>
        </p>
          <p>
Two main things to bring to the wedding:<br />
1. A sun hat if it's hot<br />
2. A bouquet of flowers.  We are asking all our guests to please bring some flowers to the wedding. If you have a garden, we'd love it if you brought flowers from there. If your neighbours have a garden... The only rule is please don't spend more than $15. When you arrive, drop the flowers off at the 'flower table'. We'll have lots and lots of vases filled with water, and we'll use your flowers to decorate and bring colour and smell to the wedding. And of course, don't worry about this if it's not convenient. 
</p>
          
          
          
          <p>
          <span class="question">How to get there</span>
        </p>
        <p>
          <span>RANSA is located at Rushcutters Bay park, with lots of transportation options nearby. They include:</span>
        </p>
        <p></p>
        <p>
          <span>Water taxi</span>
          <span>: We're putting this first because its the most fun option. You can get dropped off right at the RANSA jetty.</span>
        </p>
        <p></p>
        <p>
          <span>Train</span>
          <span>: The Edgecliffe train station on the Eastern Suburbs line is the closest stop to RANSA. The station is located at the
          top of the hill, on New South Head Road. Get out of the station, turn right on New South Head Road, and at the bottom of the
          hill turn right on New Beach Road. From there, keep walking along the park, past all the marine shops until you hit RANSA.
          Its probably a 15 minute walk from the station to RANSA. Longer going back because you have to go up the hill!</span>
        </p>
        <p></p>
        <p>
          <span>Taxi</span>
          <span>: 131 008 is the phone number for taxis combined.</span>
        </p>
        <p></p>
        <p>
          <span>Driving:</span>
          <span>Unfortunately, parking is limited close to RANSA. New Beach Road has a 2 hour parking limit, and we know from experience
          that they ticket. Your best bet for parking is at the Edgecliffe Centre car park, a 10 -15 minute walk away which is free on Sundays. </span>
        </p>
        <p></p>
        <p>
        <span>Bus:</span> 
        <span>We're sure there are busses that take you nearby but we're not familiar with them, and they will probably be different
        depending on where you are coming from.</span> 
        <br />
        <span class="c5">
          <a class="c6"
          href="http://www.transportnsw.info">
          http://www.transportnsw.info/</a>
        </span>
        <span>is your best site for door to door public transport routes.</span></p>
        <p></p>