    <h1>FAQs</h1>
     
        <p>
          <span class="question">What do I wear?</span>
        </p>
        <p>
          <span>Wear what makes you comfortable and that you can dance in! This is a sunny (hopefully) Sunday afternoon kind of
          wedding, so we're not planning on getting super dressed up. You can if you want, though!</span>
        </p>
        <p></p>
        <p>
          <span>One note of caution for women (or anyone else coming who might wear heels) - we recommend against stilettos. Between
          the grass outside and the slatted wooden floor at RANSA, you might find yourself stuck! Chunkier heels or flats are
          best.</span>
        </p>
        <p></p>
        <p>
          <span class="question">What about my dietary restrictions?</span>
        </p>
        <p>
          <span>Let us know! Lunch will be a buffet with meat, fish and veggie options. If you have other food allergies or restrictions,
          please let us know so that we can arrange food for you accordingly.</span>
        </p>
        <p></p>
        <p>
          <span class="question">What do I do with the kiddies?</span>
        </p>
        <p>
          <span>Tamara has lots of littlies as cousins so we're working on pulling a list together of great babysitters. Check back
          here for more information over the coming weeks. If you need info before then, drop us a line and we'll get back to you with
          some recommendations.</span>
        </p>
        <p></p>
        <p>
          <span class="question">Do I need a car?</span>
        </p>
        <p>
          <span>Absolutely not. In fact, if you look here <a href="http://rsvp.eartown.com/ceremony">The Event</a>, you'll see that not only is
          parking somewhat limited, there are also lots of public transport options to get here.</span>
        </p>
          <p>
          <span class="question">What about presents? Are you registered anywhere?</span>
        </p>
        <p>

If you wish to buy us a present, we're registered at Peters of Kensington*. We'd also appreciate anything from the heart or a contribution to our honeymoon (fingers crossed for an around the world trip). All we really need, however, is you. No presents are necessary.  
        </p>
        <p>
            *View and purchase from our gift registry only at <a href="http://www.petersofkensington.com.au">www.petersofkensington.com.au</a>. Enter either Heydon or Heligman and the event date at the top of the page. You can also make purchases at the store or by phone. Address is 57 Anzac Parade, Kensington NSW 2033
        </p>