<h1>Things to do in Sydney</h1>
<p>
Here are some of our Sydney recommendations
</p>
<p>
If this is your first time in Sydney, it’s well worth checking out the Botanic gardens, the Domain, the Opera House and Circular Quay. They are all near each other and can be done in a day trip. When you're at the Domain, walk all the way to the edge of the point, past the art Gallery to Lady Macquarie's Chair. It's a beautiful view. There are also some very good museums in the area- The Art Gallery of NSW has a great selection of Australian and international art. It's a nice size too- a lot to see but not overwhelming. The Museum of Contemporary Art has been renovated in the past few years and has a great collection and often has an interesting temporary exhibit. Again, it's a really doable size and is right on Circular Quay so we recommend checking it out while you're already down there.
</p>
<p>
Ferries: It's 100% worth it to take a ferry someplace. Either use them to get where you want to go or just take a round trip to get out on the Harbour. A nice day trip includes the ferry to Manly, a walk and a swim at the beach and then get the ferry back. Alternatively, if you’re looking for a great walk, you can take the ferry to Manly, then do the Manly to Spit walk (this is a GORGEOUS easy walk that take about 3? hours http://www.manlyaustralia.com.au/information/what_to_do/walks/walkway.asp) along the Harbour and then get a bus from the Spit back to the city. You could also do this in the opposite direction, of course.
</p>
<p>
Beaches: Australian beaches are magnificent. Sydney has two strips of beaches- the Northern Beaches of which Manly is the most famous, and the Southern beaches of which Bondi is the most famous. The Southern Beaches are easier to get to and consequently the area around them is a lot more populated. Even if you go to Manly, you still may want to take a day and going out to Bondi. There's a walk along the beaches from Bondi to Coogee. You can do the whole thing or do the shorter route Bondi to Bronte. They're easy walks along the coast and are truly beautiful in any weather. Tamara’s favourite breakfast joint in all Sydney is also in Bondi. It's a bit pricey but worth it. It's called Trio and is along Campbell Parade (the main drag along the beach).
</p>
<p>
Some of our favourite, centrally located restaurants are:<br/>
Spice I Am in Surry Hills on Wentworth St- Best thai food in Sydney. Really spicy. Just delicious. <br/>
House: This is owned by the same folks as Spice I am. It's northern thai food and is also good but quite different from he usual fare. It's right near Central, around the corner from Spice I am. <br/>
The Athenian: Yummy greek food right in the CBD, off George Street. Huge portions. We recommend the lamb and eggplant.<br/>
Nakashima in the Rocks- I'm 99% sure I have the name of this restaurant right. It's a reasonably priced Japanese place which is really yummy and located in the Rocks which is a worthwhile area to explore- beautiful old terrace houses.<br/>
Fratelli Fresh: Beautiful Italian food. There are a few of these about. The one we've been to is near the Rocks in Walsh Bay.<br/>
Yullis: Vegetarian food in Surry Hills with an amazing beer selection<br/>
Also, ask us about our local favourites around Ashfield (Chinese and Japanese restaurants) and Haberfield (Italian).
</p>
<p>

And, if you have a bit more time to get outside of Sydney and you like walking, we recommend you head out to either Royal National Park or the Blue Mountains (or both). Both are about 1-2 hours away and you can get there by public transportation (although car will give you a bit more flexibility in the walks you can do).  If you end up going, let us know and we’ll give you more detail.
</p>