
    <p>
          <h1>TYING THE KNOT</h1>
        </p>
        <p>
          <span>G&amp;T: 23 November 2014</span>
        </p>

        <p>
          <span>Insert photo of us</span>
        </p>
        <p></p>
        <p>
          <span>We cant wait to celebrate with you in November. Well continue to update this page with information about the wedding,
          where to stay, and things to do in the beautiful city of Sydney.</span>
        </p>
        <p></p>
