<div class="response1 content">
    <div class="please">
       Please RSVP by 20 October 2014.
    </div>
    
    <div class="next">
        <a href="<?php echo $this->url(array("step" => 2), 'rsvp-respond'); ?>">
            <button type="button" class="btn btn-primary btn-success">RSVP here</button>
        </a>
    </div>
    <div class="invite">
        <a href="<?php echo $this->url(array("step" => 2), 'rsvp-respond'); ?>">
            <img class="img-responsive" src="/images/invite_boats.jpg" />
        </a>
    </div>
    
</div>

   