<h1>Success</h1>
<?php echo implode($this->messages) ?>
    <br />
    If you have any questions or wish to send a message you can email <a href="mailto:tgheligman@gmail.com">Tamara</a> or <a href="mailto:tgheligman@gmail.com">George</a>.
      <br />
      Please check out the rest of our website for more information about the wedding, including how to get there, where to stay and things to do in Sydney. 