<h2>List Families</h2>
<a href="/admin/rsvp/family/create">Add Family</a><br />
<br />
<?php if (count($this->records)): ?>
<div id="records">
        <table>
            <tr>
                <td class="key">
                    ID
                </td>
                <td class="key">
                    Primary Contact 
                </td>                
                <td class="key">
                    Contact email
                </td>
                <td></td>
            </tr>
            <?php foreach($this->records as $r): ?>
            <tr>
                <td>
                    <?php echo $this->escape($r['fid']); ?>
                </td>
                <td>
                    <?php echo $this->escape($r['Wedding_Model_Guest']['firstname']); ?>
                </td>
                <td>
                    <?php echo $this->escape($r['Wedding_Model_Guest']['email']); ?>
                </td>
                <td>
                    <a href="/rsvp/invite/<?php echo $this->escape($r['fid']); ?>">View Invite</a>
                </td>
            </tr>
            <?php endforeach; ?>
        </table>
</div>

<?php else: ?>
No records found.
<?php endif; ?>
