<br />
Dear <?php echo $this->name ?>,<br />
<br />
Click to open your invite: <br /><br />
<a href="http://rsvp.eartown.com/autologin/<?php echo $this->fid ?>/<?php echo $this->code ?>"><img src="http://rsvp.eartown.com/rsvp/image/<?php echo $this->fid ?>/envelope3.jpg" /></a><br />
<br />
<a href="http://rsvp.eartown.com/autologin/<?php echo $this->fid ?>/<?php echo $this->code ?>">View invitation</a><br />
<br />

From George and Tamara 